### ISSUE TITLE
Why the data folder have no data files?

### ISSUE THREAD

**Issue by ghost** [johli/aparent#2]
Hi, I am researching on your paper recently, but when I want to reproduct your codes, I have found that no data is in the project. I have download the dataset according to the website you offer in the readme, but I don't konw how to use it.

**Comment by johli** [comment]
Hi,

The data folders in the github repo are intended to provide the structure expected by the different analysis/training scripts to run properly. However, it is inefficient/bad practice to put large GB-sized data files in the github repo, which is why we decided to compress and upload the actual data files to a google drive instead.

So, the google drive https://drive.google.com/drive/folders/1qex3oY-rarsd7YowM7TxxUklLbLkUyOT contains tar.gz-archives of the data files, and the folder/archive structure in the drive is identical to that of the data/ folder in the github repo. To use the data, you should download the entire google drive, uncompress all of the archives, and place them in the corresponding locations in the github file structure under the data/ root folder.

For example, you should uncompress the .tar.gz-archive from prepared_data/ in the google drive to the folder data/prepared_data/ in the github repo.

Let me know if you run into any issues.

Best,

Johannes

**Comment by ghost** [comment]
Dear Johannes:

Thank you for your detail reply. Your code is so elegant that i can easily understand. 

I have found that what you say about the data. But I have a doubt why you write "The Legacy Data is the version of the processed data analyzed in the paper, which we provide here for reproducibility." in the README. So I thought the "Processed Data Repository (legacy)" is what i need for reproducibility, but the truth is the "Processed Data Repository" that i really need. 

Forgive me if my language seems rude, because my English is really poor.

Thank you very much for your reply.

Best,

Zhao Chao
