### ISSUE TITLE
Potential PolyA Detector scoring issue

### ISSUE THREAD

**Issue by biostu24** [johli/aparent#3]
Hi there, 

I cloned the APARENT repo to run the polyA detector (`score_polya_peaks`) locally. I used the "Notebook 3: PolyA Peak Detection" Jupyter notebook as a guide to get started. However, running the code using the example data I got different results with the `peak_iso_scores` function, specifically the last score. The notebook suggested I should detect 3 peaks with the following logit scores:

```Peak PAS scores (log odds) = [2.413, 0.965, 1.688]```

The results I get are:

```Peak PAS scores (log odds) = [2.413, 0.965, -10]```
with the last score being -10 vs. 1.688 in the Jupyter notebook. 

Investigating further, using different sequences, I found I always get -10 as my last peak score. E.g. If I use a sequence with one peak, the score is -10. If I use a sequence with 6 peaks, again the last score is -10. This true for a sequence that contained previously a high scoring peak. 

I then checked this against web tool (https://apa.cs.washington.edu/detect) which gives the same results, always giving a score of -10 for the last detected peak. This can be reproduced using the example sequence in the Jupyter notebook. So this issue is not due to my particular system setup. 

I don't believe this is the intended behaviour. Let me know if you want me to post my system details.

**Comment by johli** [comment]
Hi,

I apologize for the late reply.
I had previously fixed a bug in the backend prediction script for the PAS pA peak detector, but had forgotten to update the example usage script.

Long story short: The predictor needs a few more nucleotides of padding for the most distal peak at position 1497. The peak script is still able to detect it, but to properly score its strength, more padding is needed since we need to slide APARENT in a window surrounding the peak. If you pad the example sequence with >=40 extra nucleotides, it should start working.

In general, if a peak is detected too close to the end of the sequence, the detector might still detect the peak, but output score -10 if there is not enough padding to confidently score the peak strength. NaN would be a better output value, but that unfortunately messes up some of the plots.

I'll update the example script and make a note of this behavior inside the script + website. Thanks for catching this!

Best,

Johannes

**Comment by biostu24** [comment]
Hi Johannes, 

Thanks for the update on the behaviour - good to know this is not a bug.
